// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&lOVQPOOOOQO'#Cb'#CbOVQPO'#CcOOQO'#Cf'#CfObQPO'#CeOOQO'#Cd'#CdO]QPO'#CaOOQO'#Ca'#CaO|QPO'#C`O![QPO'#C_OOQO'#C^'#C^QOQPOOO!gQPO,58}OOQO'#Ch'#ChOOQO'#Cm'#CmO!lQPO'#CmO!qQQO,59PO#PQPO,59POOQO,58{,58{OOQO'#Cp'#CpOVQPO'#CsO#UQPO,58zOOQO'#Cq'#CqOVQPO'#CtO#dQPO,58yOOQO1G.i1G.iOOQO,59X,59XOOQO'#Cl'#ClOOQO'#Ci'#CiOOQO1G.k1G.kO!qQQO'#CnOOQO,59_,59_OOQO-E6q-E6qOOQO,59`,59`OOQO-E6r-E6rOOQO'#Co'#CoO#oQPO,59YO!qQQO'#CrO#wQPO1G.tOOQO1G.t1G.tOOQO,59^,59^OOQO-E6p-E6pOOQO7+$`7+$`",
  stateData: "$P~OkOS~OZROlPOmQO~Ol_Oo]Op]Oq]Or]Os]Ot]Ow^O~OycOiSXzSXnSX~OzfOiRXnRX~OniO~OwjO~O^lO_lOukOvkO~OmnO~OycOiSazSanSa~OzfOiRanRa~OnwOxuO~OnzOxuO~O",
  goto: "#}iPPjpt{!T!Z!d!j!pP!v!yPP#Q#V#Y#]#c#g#k#q#wQZOR[QTYOQSXOQRqgUWOQgRodXUOQdgWTOQdgRbUXVOQdgXTOQdgXSOQdgR`SQm`TsnuVl`nuRaSRmaQtnRxuTdWeTgXhQvtRyvQeWRpeQhXRrh",
  nodeNames: "⚠ Query Expression OrExpression AndExpression NotExpression NotOp Group Primary Comparison Field Identifier CompareOperator ScalarValue String Number Boolean InOperator ListLiteral ListItem AndOp OrOp",
  maxTerm: 42,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",|~RgXY!jYZ!j]^!jpq!jqr!{rs#Wxy$zyz%P|}%U!Q![%Z!^!_%t!_!`&R!`!a&W!c!d&e!k!l&v!p!q'R!q!r'd#R#S'o#T#Y'o#Y#Z(T#Z#h'o#h#i*t#i#o'o~!oSk~XY!jYZ!j]^!jpq!j~#OP!_!`#R~#WOp~~#ZWOY#WZr#Wrs#ss#O#W#O#P#x#P;'S#W;'S;=`$t<%lO#W~#xO^~~#{RO;'S#W;'S;=`$U;=`O#W~$XXOY#WZr#Wrs#ss#O#W#O#P#x#P;'S#W;'S;=`$t;=`<%l#W<%lO#W~$wP;=`<%l#W~%POm~~%UOn~~%ZOx~~%`Q_~!O!P%f!Q![%Z~%iP!Q![%l~%qP_~!Q![%l~%yPs~!_!`%|~&ROt~~&WOo~~&]Pq~!_!`&`~&eOr~~&hP!p!q&k~&nP!f!g&q~&vOy~~&yP!p!q&|~'ROw~~'UP!q!r'X~'[P!v!w'_~'dOl~~'gP!t!u'j~'oOz~P'tTZP}!O'o!O!P'o!Q!['o#R#S'o#T#o'oR(YUZP}!O'o!O!P'o!Q!['o#R#S'o#T#U(l#U#o'oR(qVZP}!O'o!O!P'o!Q!['o#R#S'o#T#`'o#`#a)W#a#o'oR)]VZP}!O'o!O!P'o!Q!['o#R#S'o#T#g'o#g#h)r#h#o'oR)wVZP}!O'o!O!P'o!Q!['o#R#S'o#T#X'o#X#Y*^#Y#o'oR*eTvQZP}!O'o!O!P'o!Q!['o#R#S'o#T#o'oR*yVZP}!O'o!O!P'o!Q!['o#R#S'o#T#f'o#f#g+`#g#o'oR+eVZP}!O'o!O!P'o!Q!['o#R#S'o#T#i'o#i#j+z#j#o'oR,PVZP}!O'o!O!P'o!Q!['o#R#S'o#T#X'o#X#Y,f#Y#o'oR,mTuQZP}!O'o!O!P'o!Q!['o#R#S'o#T#o'o",
  tokenizers: [0, 1],
  topRules: {"Query":[0,1]},
  tokenPrec: 0
})
