// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&lOVQPOOOOQO'#Cb'#CbOOQO'#Ce'#CeObQPO'#CdOVQPO'#CoOOQO'#Cc'#CcOVQPO'#CaOOQO'#Ca'#CaO|QPO'#C`O![QPO'#C_OOQO'#C^'#C^QOQPOOOOQO'#Cg'#CgOOQO'#Cl'#ClO!gQPO'#ClO!lQQO,59OO!zQPO,59OO#PQPO,59ZOOQO,58{,58{OOQO'#Cp'#CpOVQPO'#CsO#UQPO,58zOOQO'#Cq'#CqOVQPO'#CtO#dQPO,58yOOQO,59W,59WOOQO'#Ck'#CkOOQO'#Ch'#ChOOQO1G.j1G.jO!lQQO'#CmOOQO1G.u1G.uOOQO,59_,59_OOQO-E6q-E6qOOQO,59`,59`OOQO-E6r-E6rOOQO'#Cn'#CnO#oQPO,59XO!lQQO'#CrO#wQPO1G.sOOQO1G.s1G.sOOQO,59^,59^OOQO-E6p-E6pOOQO7+$_7+$_",
  stateData: "$P~OkOS~OYQOlPOvSO~Ol^Om[On[Oo[Op[Oq[Or[Ou]O~OycOiSXzSXxSX~OzfOiRXxRX~OuiO~O]kO^kOsjOtjO~OvmO~OxnO~OycOiSazSaxSa~OzfOiRaxRa~OwuOxwO~OwuOxzO~O",
  goto: "#{iPPjpt{!W!_!f!mP!t!wPP#O#T#W#Z!f#a#e#i#o#uQZORaSTYOSSXOSRqgUWOSgQbURodZUOSUdgZVOSUdgZTOSUdgZROSUdgR_RQl_TsmuVk_muR`RRl`QtmRxuTdWeTgXhQvtRyvQeWRpeQhXRrh",
  nodeNames: "⚠ Query Expression OrExpression AndExpression NotExpression NotOp Primary Comparison Field Identifier CompareOperator ScalarValue String Number Boolean InOperator ListLiteral ListItem Group AndOp OrOp",
  maxTerm: 42,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",|~RgXY!jYZ!j]^!jpq!jqr!{rs#Wxy$zyz%P|}%U!Q![%Z!^!_%t!_!`&R!`!a&W!c!d&e!k!l&v!p!q'R!q!r'd#R#S'o#T#Y'o#Y#Z(T#Z#h'o#h#i*t#i#o'o~!oSk~XY!jYZ!j]^!jpq!j~#OP!_!`#R~#WOn~~#ZWOY#WZr#Wrs#ss#O#W#O#P#x#P;'S#W;'S;=`$t<%lO#W~#xO]~~#{RO;'S#W;'S;=`$U;=`O#W~$XXOY#WZr#Wrs#ss#O#W#O#P#x#P;'S#W;'S;=`$t;=`<%l#W<%lO#W~$wP;=`<%l#W~%POv~~%UOx~~%ZOw~~%`Q^~!O!P%f!Q![%Z~%iP!Q![%l~%qP^~!Q![%l~%yPq~!_!`%|~&ROr~~&WOm~~&]Po~!_!`&`~&eOp~~&hP!p!q&k~&nP!f!g&q~&vOy~~&yP!p!q&|~'ROu~~'UP!q!r'X~'[P!v!w'_~'dOl~~'gP!t!u'j~'oOz~P'tTYP}!O'o!O!P'o!Q!['o#R#S'o#T#o'oR(YUYP}!O'o!O!P'o!Q!['o#R#S'o#T#U(l#U#o'oR(qVYP}!O'o!O!P'o!Q!['o#R#S'o#T#`'o#`#a)W#a#o'oR)]VYP}!O'o!O!P'o!Q!['o#R#S'o#T#g'o#g#h)r#h#o'oR)wVYP}!O'o!O!P'o!Q!['o#R#S'o#T#X'o#X#Y*^#Y#o'oR*eTtQYP}!O'o!O!P'o!Q!['o#R#S'o#T#o'oR*yVYP}!O'o!O!P'o!Q!['o#R#S'o#T#f'o#f#g+`#g#o'oR+eVYP}!O'o!O!P'o!Q!['o#R#S'o#T#i'o#i#j+z#j#o'oR,PVYP}!O'o!O!P'o!Q!['o#R#S'o#T#X'o#X#Y,f#Y#o'oR,mTsQYP}!O'o!O!P'o!Q!['o#R#S'o#T#o'o",
  tokenizers: [0, 1],
  topRules: {"Query":[0,1]},
  tokenPrec: 0
})
